#! /bin/bash

# Uninstall any old versions
echo "Removing any old Docker packages"
echo "You can ignore errors"
sudo yum remove docker \
  docker-common \
  container-selinux \
  docker-selinux \
  docker-engine \
  docker-compose

# Set up the Docker CE repository on CentOS:
echo "Adding the Docker CE repository"
sudo yum install -y yum-utils
sudo yum-config-manager \
  --add-repo \
  https://download.docker.com/linux/centos/docker-ce.repo
sudo yum makecache fast

# Install the latest version of Docker CE on CentOS:
echo "Installing Docker CE"
sudo yum -y install \
  docker-ce

# Docker Compose
echo "Installing Docker Compose 1.11.2"
curl -Ls https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` \
  > docker-compose
sudo mv docker-compose /usr/local/bin
sudo chmod +x /usr/local/bin/docker-compose

# Start Docker:
echo "Enabling and starting Docker"
sudo mkdir -p /etc/docker/
sudo cp daemon.json /etc/docker/ # specify storage driver
sudo systemctl enable docker
sudo systemctl start docker

# Test your installation:
echo "Testing it!"
sudo docker run hello-world

# Configure "docker" group
echo "Adding ${USER} to the 'docker' group"
sudo groupadd docker
sudo usermod -aG docker ${USER}
echo "Log out and back in to join the 'docker' group."
