version: '2.1'
services:
  i2julia:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker.io/znmeb/i2julia
    user: i2julia
    command: /home/i2julia/startup.bash
    environment:
      - TERM
    ports:
      - "8888:8888"
